# Generated by Django 6.0.4 on 2026-05-01 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radio_metros', models.IntegerField(default=100)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': '"FinC"."sedes"',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.sede')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': '"FinC"."usuarios"',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora_entrada', models.DateTimeField(blank=True, null=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_break', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_break', models.DateTimeField(blank=True, null=True)),
                ('latitud_entrada', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_entrada', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('latitud_salida', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_salida', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(default='Sin Marcar', max_length=50)),
                ('dispositivo_info', models.TextField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': '"FinC"."asistencias"',
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_incidencia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='incidencias/')),
                ('fecha_hora_reporte', models.DateTimeField(auto_now_add=True)),
                ('estado_revision', models.CharField(default='Pendiente', max_length=50)),
                ('asistencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='api.asistencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'db_table': '"FinC"."incidencias"',
            },
        ),
    ]
