# Generated by Django 6.0.4 on 2026-05-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuraciontracking_rol_tipoincidencia_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asistencia',
            table='asistencias',
        ),
        migrations.AlterModelTable(
            name='asistenciaevento',
            table='asistencia_eventos',
        ),
        migrations.AlterModelTable(
            name='configuraciontracking',
            table='configuracion_tracking',
        ),
        migrations.AlterModelTable(
            name='historialjornada',
            table='historial_jornadas',
        ),
        migrations.AlterModelTable(
            name='incidencia',
            table='incidencias',
        ),
        migrations.AlterModelTable(
            name='rol',
            table='roles',
        ),
        migrations.AlterModelTable(
            name='sede',
            table='sedes',
        ),
        migrations.AlterModelTable(
            name='tipoincidencia',
            table='tipos_incidencia',
        ),
        migrations.AlterModelTable(
            name='ubicacionpunto',
            table='ubicacion_puntos',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
