# Generated by Django 6.0.4 on 2026-05-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_configuraciontracking_rol_tipoincidencia_and_more'),
    ]

    operations = [
    ]
