# Generated by Django 6.0.4 on 2026-05-07 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_asistencia_table_alter_asistenciaevento_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sedes_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sede',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sedes_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sede',
            name='referencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='creado_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='sede',
            name='radio_metros',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
