# Generated by Django 6.0.4 on 2026-05-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sede_actualizado_por_sede_codigo_sede_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
