# Generated by Django 6.0.4 on 2026-05-08 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_debe_cambiar_password_usuario_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsuarioSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_visualizar', models.BooleanField(default=True)),
                ('puede_gestionar', models.BooleanField(default=False)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='api.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario por Sede',
                'verbose_name_plural': 'Usuarios por Sede',
                'db_table': 'usuario_sedes',
                'unique_together': {('usuario', 'sede')},
            },
        ),
    ]
