# Generated by Django 6.0.4 on 2026-05-08 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_creado_por_usuariosede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='creado_por',
            field=models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
