# Generated by Django 6.0.4 on 2026-05-08 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_usuario_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='revisado_por',
            field=models.ForeignKey(blank=True, db_column='revisado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_revisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
