# Generated by Django 6.0.4 on 2026-05-13 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_incidencia_revisado_por'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('hora_inicio_marcacion', models.TimeField()),
                ('hora_fin_marcacion', models.TimeField()),
                ('hora_inicio_salida', models.TimeField(blank=True, null=True)),
                ('hora_fin_salida', models.TimeField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jornadaconfiguracion_actualizado_por_set', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.sede')),
            ],
            options={
                'verbose_name': 'Configuración de Jornada',
                'verbose_name_plural': 'Configuraciones de Jornada',
                'db_table': 'jornada_configuracion',
                'managed': True,
                'unique_together': {('sede', 'dia_semana')},
            },
        ),
    ]
