# Generated by Django 6.0.4 on 2026-05-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_jornadaconfiguracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JornadaActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('cliente_documento', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente_telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_actividad', models.TextField(blank=True, null=True)),
                ('latitud_inicio', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud_inicio', models.DecimalField(decimal_places=8, max_digits=11)),
                ('evidencia_inicio_url', models.TextField(blank=True, null=True)),
                ('dispositivo_inicio', models.TextField(blank=True, null=True)),
                ('hora_inicio_actividad', models.DateTimeField(auto_now_add=True)),
                ('latitud_fin', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud_fin', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('evidencia_fin_url', models.TextField(blank=True, null=True)),
                ('dispositivo_fin', models.TextField(blank=True, null=True)),
                ('hora_fin_actividad', models.DateTimeField(blank=True, null=True)),
                ('resultado_actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('estado_actividad', models.CharField(choices=[('en_proceso', 'En Proceso'), ('finalizada', 'Finalizada')], default='en_proceso', max_length=50)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actividad de Jornada',
                'verbose_name_plural': 'Actividades de Jornada',
                'db_table': 'jornada_actividades',
                'managed': False,
            },
        ),
    ]
