# Generated by Django 6.0.4 on 2026-05-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_jornadaactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ubicacionpunto',
            options={'ordering': ['fecha_hora'], 'verbose_name': 'Punto de Ubicación', 'verbose_name_plural': 'Puntos de Ubicación'},
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado_asistencia',
            field=models.CharField(default='programada', max_length=20),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado_puntualidad',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='historialjornada',
            name='estado_asistencia',
            field=models.CharField(default='programada', max_length=20),
        ),
        migrations.AddField(
            model_name='historialjornada',
            name='estado_puntualidad',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='usuariosede',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuariosede',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuariosede',
            name='puede_gestionar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='historialjornada',
            unique_together={('usuario', 'fecha')},
        ),
    ]
