# Generated by Django 6.0.4 on 2026-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_ubicacionpunto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado_salida',
            field=models.CharField(default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='historialjornada',
            name='estado_salida',
            field=models.CharField(default='pendiente', max_length=20),
        ),
    ]
