# Generated by Django 6.0.5 on 2026-05-27 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_asistencia_estado_salida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True, null=True)),
                ('tipo_configuracion', models.CharField(blank=True, max_length=50, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_creados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='api.sede')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
            },
        ),
        migrations.CreateModel(
            name='HorarioDetalle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(max_length=50)),
                ('hora_inicio_entrada', models.TimeField()),
                ('hora_fin_entrada', models.TimeField()),
                ('hora_inicio_salida', models.TimeField()),
                ('hora_fin_salida', models.TimeField()),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True, null=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.horario')),
            ],
            options={
                'verbose_name': 'Detalle de Horario',
                'verbose_name_plural': 'Detalles de Horarios',
                'db_table': 'horario_detalles',
            },
        ),
        migrations.CreateModel(
            name='IntercambioHorario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_intercambio', models.DateField()),
                ('estado', models.CharField(blank=True, default='aprobado', max_length=50, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('aprobado_at', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, db_column='aprobado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('horario_reemplazo_original', models.ForeignKey(blank=True, db_column='horario_reemplazo_original_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios_reemplazo_orig', to='api.horario')),
                ('horario_solicitante_original', models.ForeignKey(blank=True, db_column='horario_solicitante_original_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios_solicitante_orig', to='api.horario')),
                ('registrado_por', models.ForeignKey(blank=True, db_column='registrado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios_registrados', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intercambios', to='api.sede')),
                ('usuario_reemplazo', models.ForeignKey(db_column='usuario_reemplazo_id', on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_reemplazos', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicitante', models.ForeignKey(db_column='usuario_solicitante_id', on_delete=django.db.models.deletion.CASCADE, related_name='intercambios_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Intercambio de Horario',
                'verbose_name_plural': 'Intercambios de Horarios',
                'db_table': 'intercambios_horario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioHorario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=True, null=True)),
                ('es_principal', models.BooleanField(blank=True, default=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, db_column='actualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_horarios_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_horarios_creados', to=settings.AUTH_USER_MODEL)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_horario', to='api.horario')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_horario_sede', to='api.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Horario de Usuario',
                'verbose_name_plural': 'Horarios de Usuarios',
                'db_table': 'usuario_horarios',
            },
        ),
    ]
