# Generated by Django 4.2.30 on 2026-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_horario_horariodetalle_intercambiohorario_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='usuario',
                    name='fcm',
                    field=models.TextField(blank=True, null=True),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$ 
                    BEGIN 
                        IF NOT EXISTS (
                            SELECT 1 
                            FROM information_schema.columns 
                            WHERE table_name = 'usuarios' 
                              AND column_name = 'fcm'
                        ) THEN 
                            ALTER TABLE usuarios ADD COLUMN fcm text; 
                        END IF; 
                    END $$;
                    """,
                    reverse_sql="""
                    ALTER TABLE usuarios DROP COLUMN IF EXISTS fcm;
                    """
                )
            ]
        )
    ]
