# Generated by Django 6.0.5 on 2026-06-09 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_notificacionpush'),
    ]

    operations = [
        migrations.CreateModel(
            name='SedeCentral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sede Central',
                'verbose_name_plural': 'Sedes Centrales',
                'db_table': 'sedes_centrales',
            },
        ),
        migrations.AddField(
            model_name='sede',
            name='sede_central',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sedes', to='api.sedecentral'),
        ),
    ]
