# Generated by Django 6.0.5 on 2026-06-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sedecentral_sede_sede_central'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedecentral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='sedes_centrales/'),
        ),
        migrations.AddField(
            model_name='sedecentral',
            name='imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
